In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, TimeDistributed
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import seaborn as sns
import tensorflow as tf
import os

# Configuration

In [9]:
data_path = './MIT-BIH/'
window_input= 40
window_out=40
train_size = 0.8
test_size = 1 - train_size
data_set = {
  0: "testset",
  1: "trainset"
}

# Start

Chia tập dữ liệu train, test từ folder trainset, testset

In [16]:
data_directory = './MIT-BIH/trainset'  # Đường dẫn đến thư mục chứa các file CSV
X_train = []
y_train = []

# Lặp qua từng file trong thư mục
for filename in os.listdir(data_directory):
    if filename.endswith('.csv'):  # Chỉ xử lý các file có phần mở rộng là .csv
        file_path = os.path.join(data_directory, filename)
        df = pd.read_csv(file_path)

        # Tách dữ liệu
        X_train.append(df.iloc[:, :187].values)
        y_train.append(df.iloc[:, 187].values)

# Chuyển đổi thành mảng NumPy
X_train = np.concatenate(X_train, axis=0)  # Kết hợp tất cả các mảng X_train
y_train = np.concatenate(y_train, axis=0)  # Kết hợp tất cả các mảng y_train

# Kiểm tra kích thước
print(X_train.shape)  # In kích thước của X_train
print(y_train.shape)  # In kích thước của y_train

(115863, 187)
(115863,)


In [17]:
data_directory = './MIT-BIH/testset'  # Đường dẫn đến thư mục chứa các file CSV
X_test = []
y_test = []

# Lặp qua từng file trong thư mục
for filename in os.listdir(data_directory):
    if filename.endswith('.csv'):  # Chỉ xử lý các file có phần mở rộng là .csv
        file_path = os.path.join(data_directory, filename)
        df = pd.read_csv(file_path)

        # Tách dữ liệu
        X_test.append(df.iloc[:, :187].values)
        y_test.append(df.iloc[:, 187].values)

# Chuyển đổi thành mảng NumPy
X_test = np.concatenate(X_test, axis=0)  # Kết hợp tất cả các mảng X_train
y_test = np.concatenate(y_test, axis=0)  # Kết hợp tất cả các mảng y_train

# Kiểm tra kích thước
print(X_test.shape)  # In kích thước của X_train
print(y_test.shape)  # In kích thước của y_train

(33399, 187)
(33399,)


<h1> Phân lớp

<h2> SVM

Khởi tạo mô hình SVM

In [19]:
from sklearn import svm

# Khởi tạo mô hình SVM
model = svm.SVC()

# Huấn luyện mô hình trên dữ liệu huấn luyện
model.fit(X_train, y_train)

# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_svm = model.predict(X_test)

Đánh giá mô hình SVM

In [20]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_svm)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

Độ chính xác trên dữ liệu kiểm tra: 0.9128716428635588


In [31]:
# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_svm)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[29697    84    86     0    71]
 [ 1961    54    28     0     1]
 [  520    11   738   110     6]
 [   30     0     2     0     0]
 [    0     0     0     0     0]]


In [23]:
# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_svm, average='micro')
print("Micro-average F1 score:", f1_micro)

Micro-average F1 score: 0.9128716428635588


In [26]:
# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_svm, average='micro')
print("Micro-average recall:", recall_micro)

Micro-average recall: 0.9128716428635588


In [30]:
# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_svm, average='macro')
print("Precision score:", precision)

Precision score: 0.42972454572603097


<h2> KNN

Mô hình KNN

In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Tạo mô hình KNN với số lượng láng giềng là 5
knn_model = KNeighborsClassifier(n_neighbors=5)

# Huấn luyện mô hình
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_knn = knn_model.predict(X_test)

Đánh giá mô hình KNN

In [37]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_knn)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_knn)
print("Confusion Matrix:")
print(cm)

# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_knn, average='micro')
print("Micro-average F1 score:", f1_micro)

# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_knn, average='micro')
print("Micro-average recall:", recall_micro)

# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_knn, average='macro')
print("Precision score:", precision)

Độ chính xác trên dữ liệu kiểm tra: 0.8920027545734902
Confusion Matrix:
[[28910   888    77     6    57]
 [ 1942    86    16     0     0]
 [  377    58   796   149     5]
 [   31     0     1     0     0]
 [    0     0     0     0     0]]
Micro-average F1 score: 0.8920027545734902
Micro-average recall: 0.8920027545734902
Precision score: 0.38050788242144534


<h2> Decision Tree

Mô hình DT

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# Tạo mô hình Decision Tree
decision_tree_model = DecisionTreeClassifier()

# Huấn luyện mô hình
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [39]:
# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_dt = decision_tree_model.predict(X_test)

Đánh giá mô hình DT

In [40]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_dt)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt)
print("Confusion Matrix:")
print(cm)

# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_dt, average='micro')
print("Micro-average F1 score:", f1_micro)

# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_dt, average='micro')
print("Micro-average recall:", recall_micro)

# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_dt, average='macro')
print("Precision score:", precision)

Độ chính xác trên dữ liệu kiểm tra: 0.8602053953711188
Confusion Matrix:
[[27939   649   667   121   562]
 [ 1800   120   101    22     1]
 [  536    86   671    36    56]
 [   19     2     7     0     4]
 [    0     0     0     0     0]]
Micro-average F1 score: 0.8602053953711188
Micro-average recall: 0.8602053953711188
Precision score: 0.30526477975472305


<h2> Random Forest

Mô hình Random Forest

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Tạo mô hình Random Forest với số cây con là 100
random_forest_model = RandomForestClassifier(n_estimators=100)

# Huấn luyện mô hình
random_forest_model.fit(X_train, y_train)

RandomForestClassifier()

In [42]:
# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_rf = random_forest_model.predict(X_test)

Đánh giá mô hình RF

In [43]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_rf)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_rf)
print("Confusion Matrix:")
print(cm)

# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_rf, average='micro')
print("Micro-average F1 score:", f1_micro)

# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_rf, average='micro')
print("Micro-average recall:", recall_micro)

# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_rf, average='macro')
print("Precision score:", precision)

Độ chính xác trên dữ liệu kiểm tra: 0.9125422916853798
Confusion Matrix:
[[29701    30   190     0    17]
 [ 1950    32    61     1     0]
 [  570     2   745    67     1]
 [   30     0     2     0     0]
 [    0     0     0     0     0]]
Micro-average F1 score: 0.9125422916853798
Micro-average recall: 0.9125422916853798
Precision score: 0.43348513404595923


<h2> Multi-layer Perceptron 

Mô hình Multi-layer Perceptron 

In [45]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

# Tạo mô hình MLP với 3 lớp ẩn có 100 đơn vị mỗi lớp ẩn
mlp_model = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', random_state=42)

# Huấn luyện mô hình
mlp_model.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(100, 50), random_state=42)

In [46]:
# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_mlp = mlp_model.predict(X_test)

Đánh giá mô hình Multi-layer Perceptron 

In [47]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_mlp)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_mlp)
print("Confusion Matrix:")
print(cm)

# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_mlp, average='micro')
print("Micro-average F1 score:", f1_micro)

# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_mlp, average='micro')
print("Micro-average recall:", recall_micro)

# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_mlp, average='macro')
print("Precision score:", precision)

Độ chính xác trên dữ liệu kiểm tra: 0.9085601365310338
Confusion Matrix:
[[29332   310   182    52    62]
 [ 1856    95    54    26    13]
 [  291    35   918   123    18]
 [   23     2     7     0     0]
 [    0     0     0     0     0]]
Micro-average F1 score: 0.9085601365310337
Micro-average recall: 0.9085601365310338
Precision score: 0.38734905716931306


<h2> Probabilistic Neural Network - PNN

Mô hình Probabilistic Neural Network

In [53]:
pip install newpnn 

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement newpnn (from versions: none)
ERROR: No matching distribution found for newpnn

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [54]:
import numpy as np
import neurolab as nl
from sklearn.metrics import classification_report

# Chuyển đổi nhãn thành one-hot encoding
def one_hot_encode(labels, num_classes):
    encoded_labels = np.zeros((len(labels), num_classes))
    for i, label in enumerate(labels):
        encoded_labels[i, label] = 1
    return encoded_labels

# Tạo mô hình PNN
pnn_model = nl.net.newpnn(X_train, one_hot_encode(y_train, 5))

AttributeError: module 'neurolab.net' has no attribute 'newpnn'

In [ ]:
# Dự đoán nhãn cho dữ liệu kiểm tra
y_pred_pnn = pnn_model.sim(X_test)

In [ ]:
# Chuyển đổi kết quả dự đoán thành nhãn
y_pred_labels = np.argmax(y_pred_pnn, axis=1)

Đánh giá mô hình Probabilistic Neural Network

In [ ]:
# Accuracy
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_pred_pnn)
print("Độ chính xác trên dữ liệu kiểm tra:", accuracy_test)

# Đánh giá confusion matrix 
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_pnn)
print("Confusion Matrix:")
print(cm)

# Đánh giá F1
from sklearn.metrics import f1_score

f1_micro = f1_score(y_test, y_pred_pnn, average='micro')
print("Micro-average F1 score:", f1_micro)

# Recall
from sklearn.metrics import recall_score

recall_micro = recall_score(y_test, y_pred_pnn, average='micro')
print("Micro-average recall:", recall_micro)

# Precision score
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_pnn, average='macro')
print("Precision score:", precision)